-- Sample data for Negari Platform
-- This file contains sample scholarships, success stories, and announcements

-- Sample Scholarships
INSERT INTO public.scholarships (title, description, provider, country, university, field_of_study, degree_level, amount_min, amount_max, currency, application_deadline, requirements, eligibility_criteria, application_url, rating, difficulty_level, featured, is_active) VALUES
('Fulbright Foreign Student Program', 'The flagship international educational exchange program sponsored by the U.S. government and is designed to increase mutual understanding between the people of the United States and the people of other countries.', 'U.S. State Department', 'United States', 'Various Universities', ARRAY['All Fields'], ARRAY['master','phd'], 25000, 50000, 'USD', '2024-10-15', ARRAY['Bachelor''s degree','English proficiency','Leadership experience'], ARRAY['Ethiopian citizenship','Academic excellence','Return to home country for 2 years'], 'https://foreign.fulbrightonline.org', 4.8, 'very_hard', true, true),

('Chevening Scholarships', 'UK government''s global scholarship programme, funded by the Foreign and Commonwealth Office (FCO) and partner organisations.', 'UK Government', 'United Kingdom', 'Various UK Universities', ARRAY['All Fields'], ARRAY['master'], 30000, 45000, 'GBP', '2024-11-02', ARRAY['Bachelor''s degree','Work experience','English proficiency'], ARRAY['Ethiopian citizenship','Leadership potential','Return to home country'], 'https://www.chevening.org', 4.7, 'very_hard', true, true),

('DAAD Scholarships', 'The German Academic Exchange Service offers scholarships for international students to study in Germany.', 'DAAD', 'Germany', 'Various German Universities', ARRAY['Engineering','Sciences','Business'], ARRAY['master','phd'], 850, 1200, 'EUR', '2024-12-31', ARRAY['Bachelor''s degree','German or English proficiency','Research proposal'], ARRAY['Academic excellence','Relevant field of study'], 'https://www.daad.de', 4.5, 'hard', true, true),

('Erasmus Mundus Joint Master Degrees', 'EU-funded international study programmes jointly delivered by an international consortium of higher education institutions.', 'European Union', 'Various European Countries', 'Multiple Universities', ARRAY['Engineering','Computer Science','Environmental Science'], ARRAY['master'], 1000, 1000, 'EUR', '2024-01-15', ARRAY['Bachelor''s degree','English proficiency','Statement of purpose'], ARRAY['Academic excellence','Non-EU citizenship'], 'https://ec.europa.eu/programmes/erasmus-plus', 4.3, 'hard', false, true),

('Australia Awards Scholarships', 'Long-term development scholarships for study at participating Australian universities and Technical and Further Education (TAFE) institutions.', 'Australian Government', 'Australia', 'Various Australian Universities', ARRAY['Development Studies','Public Policy','Engineering'], ARRAY['bachelor','master'], 25000, 35000, 'AUD', '2024-04-30', ARRAY['Academic transcripts','English proficiency','Health clearance'], ARRAY['Ethiopian citizenship','Development focus','Return to home country'], 'https://www.australiaawards.gov.au', 4.4, 'hard', false, true),

('Swedish Institute Scholarships', 'Scholarships for global professionals to pursue master''s studies in Sweden.', 'Swedish Institute', 'Sweden', 'Various Swedish Universities', ARRAY['Environment','Peace Studies','Human Rights'], ARRAY['master'], 10000, 15000, 'SEK', '2024-02-15', ARRAY['Bachelor''s degree','Work experience','English proficiency'], ARRAY['Leadership experience','Development focus'], 'https://si.se/en/apply/scholarships-and-grants', 4.2, 'medium', false, true),

('New Zealand Development Scholarships', 'Scholarships for students from developing countries to study in New Zealand.', 'New Zealand Aid Programme', 'New Zealand', 'Various NZ Universities', ARRAY['Agriculture','Health','Education'], ARRAY['bachelor','master'], 20000, 30000, 'NZD', '2024-03-31', ARRAY['Academic excellence','English proficiency','Development focus'], ARRAY['Developing country citizenship','Return commitment'], 'https://www.nzscholarships.govt.nz', 4.1, 'medium', false, true),

('Korea Government Scholarship Program', 'Scholarships offered by the Korean government for international students.', 'Korean Government', 'South Korea', 'Various Korean Universities', ARRAY['Technology','Business','Korean Studies'], ARRAY['bachelor','master','phd'], 800, 1000, 'USD', '2024-05-31', ARRAY['Academic transcripts','Health certificate','Language proficiency'], ARRAY['Academic excellence','Korean language learning commitment'], 'https://www.studyinkorea.go.kr', 4.0, 'medium', false, true),

('Japanese Government (MEXT) Scholarships', 'Scholarships provided by the Japanese Ministry of Education, Culture, Sports, Science and Technology.', 'Japanese Government', 'Japan', 'Various Japanese Universities', ARRAY['Technology','Sciences','Japanese Studies'], ARRAY['bachelor','master','phd'], 1000, 1500, 'USD', '2024-06-30', ARRAY['Academic excellence','Japanese language aptitude','Research plan'], ARRAY['Academic merit','Age requirements'], 'https://www.mext.go.jp', 4.2, 'hard', false, true),

('Netherlands Fellowship Programmes', 'Scholarships for professionals from developing countries to study in the Netherlands.', 'Netherlands Government', 'Netherlands', 'Various Dutch Universities', ARRAY['Water Management','Governance','Health'], ARRAY['master'], 5000, 25000, 'EUR', '2024-02-01', ARRAY['Bachelor''s degree','Work experience','English proficiency'], ARRAY['Professional experience','Development focus'], 'https://www.nuffic.nl/en/subjects/nfp', 3.9, 'medium', false, true);

-- Sample Success Stories
INSERT INTO public.success_stories (title, student_name, university, country, field_of_study, degree_level, scholarship_received, story_content, key_advice, timeline_years, original_city, current_status, featured, approved) VALUES
('From Addis Ababa to Harvard: My Journey in Public Health', 'Hana Tesfaye', 'Harvard University', 'United States', 'Public Health', 'master', 'Fulbright Scholarship', 'Growing up in Addis Ababa, I always dreamed of making a difference in healthcare. After completing my undergraduate degree in Biology at Addis Ababa University, I worked for two years at a local NGO focusing on maternal health. This experience opened my eyes to the global health challenges our country faces and motivated me to pursue advanced studies abroad.

The application process was challenging but rewarding. I spent months preparing for the TOEFL, writing my statement of purpose, and gathering recommendation letters. The Fulbright interview was intense, but my passion for public health and clear vision for how I would use my education to benefit Ethiopia helped me succeed.

Now at Harvard, I''m specializing in global health policy with a focus on maternal and child health in developing countries. The resources and networking opportunities here are incredible. I''ve connected with researchers working on similar issues in Africa and have already started collaborating on a project to improve healthcare delivery in rural Ethiopian communities.

My advice to fellow students: start early, be persistent, and never lose sight of your goals. The journey is challenging but absolutely worth it.', ARRAY['Start your application process at least 18 months in advance','Focus on gaining relevant work experience before applying','Practice English daily and take the TOEFL multiple times if needed','Write a compelling personal statement that shows your passion and future plans','Build relationships with professors who can write strong recommendation letters','Research your target universities and programs thoroughly'], 3, 'Addis Ababa', 'Currently studying at Harvard School of Public Health', true, true),

('Breaking Barriers: My Engineering Journey to MIT', 'Samuel Girma', 'Massachusetts Institute of Technology', 'United States', 'Electrical Engineering', 'phd', 'MIT Fellowship', 'My journey to MIT began during my undergraduate studies at Addis Ababa Institute of Technology. As one of the few students interested in renewable energy systems, I spent countless hours in the lab working on solar energy projects. My professors encouraged me to think beyond the classroom and consider graduate studies abroad.

The application process for PhD programs in the US was daunting. I had to prepare for the GRE, improve my English writing skills, and conduct research to identify potential advisors whose work aligned with my interests. I applied to 12 universities and was fortunate to receive offers from several top programs.

Choosing MIT was the best decision I''ve ever made. The research facilities are world-class, and I''m working on cutting-edge projects in renewable energy that have direct applications for Ethiopia''s energy challenges. My research focuses on developing affordable solar solutions for rural communities.

The cultural adjustment was significant, but the international student community at MIT provided great support. I''ve also been active in mentoring other Ethiopian students who are considering graduate studies abroad.', ARRAY['Excel in your undergraduate coursework and build strong relationships with professors','Gain research experience as early as possible','Prepare thoroughly for standardized tests like GRE and TOEFL','Apply to multiple universities to increase your chances','Reach out to potential advisors before applying','Stay connected with your home country and look for ways your research can make an impact there'], 5, 'Bahir Dar', 'PhD candidate at MIT, expected graduation 2025', true, true),

('Medicine and Service: My Path to Johns Hopkins', 'Meron Alemayehu', 'Johns Hopkins University', 'United States', 'Medicine', 'master', 'WHO Scholarship', 'My passion for medicine began during a volunteer experience at a rural clinic in southern Ethiopia. Seeing the healthcare disparities firsthand motivated me to pursue medical studies with a focus on global health and health systems strengthening.

After completing my medical degree at Jimma University, I worked as a general practitioner for three years while simultaneously preparing for international opportunities. The WHO scholarship program was perfect for my goals as it specifically targets healthcare professionals from developing countries.

The application required extensive documentation of my clinical experience, research background, and future career plans. The interview process was conducted virtually due to COVID-19, which actually worked in my favor as I could interview from Ethiopia.

At Johns Hopkins, I''m pursuing a Master''s in Health Systems and Policy with a concentration in global health. The program is intensive but incredibly rewarding. I''ve had the opportunity to work with WHO officials and policy makers from around the world.

My capstone project focuses on strengthening primary healthcare systems in Ethiopia, and I''m working closely with the Ethiopian Ministry of Health to ensure the research has practical applications.', ARRAY['Gain substantial work experience in your field before applying for advanced degrees','Document all your professional achievements and community service','Learn about different scholarship opportunities beyond the obvious ones','Prepare for virtual interviews as they''re becoming more common','Focus on how your studies will benefit your home country','Build a network of professionals in your field'], 2, 'Hawassa', 'Completing Master''s at Johns Hopkins, returning to Ethiopia in 2024', false, true),

('Computer Science Dreams: From Mekelle to Stanford', 'Dawit Hagos', 'Stanford University', 'United States', 'Computer Science', 'master', 'Stanford Fellowship', 'Technology has always fascinated me, even as a child growing up in Mekelle. I learned programming on my own using online resources and built several small applications during my undergraduate studies at Mekelle University.

The transition from a small university in Ethiopia to Stanford was significant. I spent two years after graduation working as a software developer while building a portfolio of projects and contributing to open-source software. This experience was crucial in strengthening my application.

Stanford''s computer science program is incredibly competitive, but my unique background and the projects I had worked on in Ethiopia helped me stand out. I emphasized how I wanted to use technology to solve problems relevant to developing countries.

Currently, I''m focusing on machine learning applications for healthcare and education. I''m part of a team developing AI-powered diagnostic tools that can work with limited internet connectivity - perfect for rural healthcare settings in Ethiopia.

The entrepreneurial environment at Stanford has also inspired me to think about starting a tech company in Ethiopia after graduation. The connections I''ve made here will be invaluable for that journey.', ARRAY['Build a strong portfolio of projects that demonstrate your skills','Contribute to open-source projects to show your coding ability','Gain work experience in the tech industry before applying to graduate school','Highlight how you plan to use your education to solve real-world problems','Network with alumni and current students at your target universities','Stay up-to-date with the latest trends in technology'], 2, 'Mekelle', 'Master''s student at Stanford, graduating in 2024', false, true);

-- Sample Announcements
INSERT INTO public.announcements (title, content, announcement_type, target_user_types, priority, is_active, expires_at) VALUES
('Welcome to Negari Platform!', 'We''re excited to have you join the Negari community! This platform is designed to guide you through your international education journey. Explore scholarships, connect with mentors, and track your progress towards your dreams.', 'general', ARRAY['starter','senior','rise','junior'], 'medium', true, '2024-12-31'),

('New Scholarship Opportunities Available', 'We''ve just added over 50 new scholarship opportunities to our database! Check out the latest Fulbright, Chevening, and DAAD scholarships for 2024. Don''t miss the application deadlines!', 'scholarship', ARRAY['starter','senior','rise','junior'], 'high', true, '2024-06-30'),

('Upcoming Application Deadlines - November 2024', 'Important reminder: Several major scholarship deadlines are approaching in November 2024. Make sure to check your application status and submit all required documents on time.', 'deadline', ARRAY['senior'], 'urgent', true, '2024-11-30'),

('New Feature: AI Essay Assistant', 'Premium users can now access our AI-powered essay assistant to help improve their scholarship application essays. This feature provides feedback on structure, content, and clarity.', 'feature', ARRAY['senior'], 'medium', true, '2024-12-31'),

('Success Story Feature Launch', 'We''re launching our Success Stories section where you can read inspiring stories from Ethiopian students who have achieved their international education dreams. Submit your own story to inspire others!', 'general', ARRAY['starter','senior','rise','junior'], 'medium', true, '2024-12-31');