// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tntxwxajgfrqoddqijum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudHh3eGFqZ2ZycW9kZHFpanVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjQ1MDksImV4cCI6MjA2NjU0MDUwOX0.bvKLvgnj6rYUOJHND5wmF8LBi8h7DAzGp5lFYxPuVEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);